#!/usr/bin/env sh
# shellcheck disable=SC1091
# shellcheck source=./_/husky.sh
. "$(dirname -- "$0")/_/husky.sh"

# TODO: There is some peerDependency not working with type:module from commitlint
# npx --no -- commitlint --edit "$1"
