#!/bin/sh
# shellcheck disable=SC1091
# shellcheck source=./_/husky.sh
. "$(dirname "$0")/_/husky.sh"

npx validate-branch-name
npm run scripts:check-commit-mail
npx lint-staged --config ./.lintstagedrc.js
npm run lint:jscpd
