#!/bin/sh
# shellcheck disable=SC1091
# shellcheck source=./_/husky.sh
. "$(dirname "$0")/_/husky.sh"

npx validate-branch-name
npm run scripts:check-commit-mail
# TODO: Those two include redundant lintings
npx lint-staged
npm run lint
