---
name: Build Patternhub

on:
  workflow_call:
    inputs:
      release:
        required: false
        default: "false"
        type: string
      preRelease:
        required: false
        default: "false"
        type: string

jobs:
  build-patternhub:
    name: Build Patternhub
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⏬ Download foundations build
        uses: actions/download-artifact@v4
        with:
          name: db-ui-foundations-build
          path: packages/foundations/build

      - name: ⏬ Download output
        uses: actions/download-artifact@v4
        with:
          name: db-ui-output
          path: output

      - name: ⏬ Download components build
        uses: actions/download-artifact@v4
        with:
          name: db-ui-components-build
          path: packages/components/build

      - name: ↔ Extract branch name
        uses: ./.github/actions/extract-branch
        id: extract_branch

      - name: ↔ Extract branch/tag name
        shell: bash
        env:
          RELEASE: ${{ inputs.release }}
          PRE_RELEASE: ${{ inputs.preRelease }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch-name }}
        run: |
          if [[ $RELEASE == "true" || $PRE_RELEASE == "true" ]]
          then
            echo "name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi
        id: extract

      - name: 🛤 Get base path
        uses: actions/github-script@v7
        env:
          NAME: ${{ steps.extract.outputs.name }}
          RELEASE: ${{ inputs.release }}
          PRE_RELEASE: ${{ inputs.preRelease }}
        id: base-path
        with:
          result-encoding: string
          script: |
            var path = 'review';
            if(process.env.RELEASE === "true" || process.env.PRE_RELEASE === "true") {
              path = 'version'
            }
            return `/${context?.payload?.repository?.name}/${path}/${process.env.NAME}`

      - name: 🔨 Build Patternhub
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ steps.base-path.outputs.result }}
        run: |
          npx --no tsx scripts/md-resolve-svg.ts
          npm run build --workspace=patternhub

      - name: ⏫ Upload Patternhub
        uses: actions/upload-artifact@v4
        with:
          name: db-ui-patternhub
          path: build-showcases/patternhub

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
